### ISSUE TITLE
Color indicator?

### ISSUE THREAD

**Issue by victordidenko** [freefelt/YouType#18] opened 2022-12-28 15:14 UTC
I use [typography layout](https://ilyabirman.ru/typography-layout/) from [Ilya Birman](https://ilyabirman.net/).

Russian and English layouts icons differs only by color:
<img width="270" alt="image" src="https://user-images.githubusercontent.com/15016227/209832688-bf60ea85-82d9-4a52-b2a5-75e1e33db3b6.png">

But YouType makes indicator grayscale, so both looks the same:
<img width="291" alt="image" src="https://user-images.githubusercontent.com/15016227/209832773-96a76031-4854-4794-99cc-71c31a21fc97.png">

Which makes it completely useless :(

**Comment by freefelt** [comment] 2022-12-29 08:29
Hello! It is because the bundle of Ilya Birman's input method has the same icons for English and Russian layouts.
You can see it by path ~/Library/Keyboard Layouts/Ilya Birman Typography Layout.bundle/Contents/Resources.
So, to resolve the problem you can just change the icns files and readd the input method.
Please, try the icns files I attached.
[ICNS.zip](https://github.com/freefelt/YouType/files/10318372/ICNS.zip)

**Comment by victordidenko** [comment] 2022-12-29 09:02
Hm, I tried, but this doesn't make any change, if YouType really makes icons grayscale:

<img width="859" alt="image" src="https://user-images.githubusercontent.com/15016227/209928350-7341f77c-11aa-4b97-8447-19972f6e1570.png">

**Comment by freefelt** [comment] 2022-12-29 09:04
Did you readd the Birman's Input method? Or you can just reboot your mac. Which version of YouType do you use?

**Comment by victordidenko** [comment] 2022-12-29 09:32
Yes. I've tried 1. simple reboot, 2. re-add Birman's Layout, 3. re-install, change icons and add layout again, 4. reboot after every previous step — nothing fixed YouType.

I have YouType version 0.7.3 from Homebrew.

If I switch off "Fix translucent indicators" I see little glitch when changing layout, maybe that will help:

https://user-images.githubusercontent.com/15016227/209932073-0e6536ca-77ee-480a-9509-871a2fea8b50.mov

**Comment by victordidenko** [comment] 2022-12-29 11:13
By the way, default icons in Ilya Birman's Layout looks the same, yes, but they are **red**. While YouType shows they as grey nonetheless.

> It is because the bundle of Ilya Birman's input method has the same icons for English and Russian layouts.
> You can see it by path ~/Library/Keyboard Layouts/Ilya Birman Typography Layout.bundle/Contents/Resources.

**Comment by victordidenko** [comment] 2022-12-29 11:17
Maybe you can add option to re-assign icons? As an escape hatch for any render issues.
So YouType will show not system, but special curated icons. For example, I explicitly want to see flags, 🇷🇺 and 🇬🇧.

**Comment by freefelt** [comment] 2022-12-29 14:18
> By the way, default icons in Ilya Birman's Layout looks the same, yes, but they are **red**. While YouType shows them as grey nonetheless.
> 
> > It is because the bundle of Ilya Birman's input method has the same icons for English and Russian layouts.
> > You can see it by path ~/Library/Keyboard Layouts/Ilya Birman Typography Layout.bundle/Contents/Resources.

It is strange, because I have only red icons)

**Comment by freefelt** [comment] 2022-12-29 14:29
> Maybe you can add option to re-assign icons? As an escape hatch for any render issues. So YouType will show not system, but special curated icons. For example, I explicitly want to see flags, 🇷🇺 and 🇬🇧.

This option will be in future updates and it will be part of the paid version, partially (the basic functionality will always be free).
Right now, you can take any png image, convert it with https://cloudconvert.com/png-to-icns to icns and replace original icons with them. But don't forget to replace ~/Library/Keyboard Layouts/Ilya Birman Typography Layout.bundle/Contents/Info.plist file with attached. There removed a isTemplate flag from eng layout.
[Info.plist.zip](https://github.com/freefelt/YouType/files/10319947/Info.plist.zip)

**Comment by freefelt** [comment] 2022-12-29 14:35
For example:
<img width="374" alt="image" src="https://user-images.githubusercontent.com/9737848/209968221-a280c434-f35d-42de-b765-cbe4ece48528.png">
[ICNS.zip](https://github.com/freefelt/YouType/files/10319981/ICNS.zip)

**Comment by victordidenko** [comment] 2022-12-29 15:38
😭
<img width="834" alt="image" src="https://user-images.githubusercontent.com/15016227/209975865-dd5a4d1f-2df6-40ad-b607-8a0d7c1c4714.png">

**Comment by freefelt** [comment] 2022-12-29 15:45
Hm, can't reproduce. What macOS version do you use?

**Comment by victordidenko** [comment] 2022-12-29 15:45
Monterey 12.6.1

**Comment by freefelt** [comment] 2022-12-29 16:05
Try to remove:
brew uninstall youtype --zap
And then install again
brew install youtype

**Comment by victordidenko** [comment] 2022-12-29 16:15
Nope, didn't help :(
I tried to change black theme to light, did't help either.
Do not know, is it macOS greyed out icons, or some other program... Tried to exit Bartender, didn't help.

**Comment by freefelt** [comment] 2022-12-29 16:24
Please, try this one
[YouType.app.zip](https://github.com/freefelt/YouType/files/10320448/YouType.app.zip)

**Comment by victordidenko** [comment] 2022-12-29 16:29
It works!

<img width="226" alt="image" src="https://user-images.githubusercontent.com/15016227/209981859-840a15d9-3563-41a2-aef1-9eec1b0e01c6.png">

**Comment by freefelt** [comment] 2022-12-29 16:40
And this one, please
[YouTypeB2.app.zip](https://github.com/freefelt/YouType/files/10320519/YouTypeB2.app.zip)

**Comment by victordidenko** [comment] 2022-12-29 16:56
This one also works :)

<img width="563" alt="image" src="https://user-images.githubusercontent.com/15016227/209984648-ef9e9356-275e-4096-9d66-96ed164fc060.png">

**Comment by freefelt** [comment] 2022-12-29 17:04
Thanks! It is strange, but the new method of detecting that the image is colored, does not work on Monterey, as it turned out. It works on Ventura, Catalina and High Sierra. But the old method works everywhere. Thanks for the feedback!

**Comment by victordidenko** [comment] 2022-12-29 17:11
I'll upgrade to Monterey 12.6.2 now, and can try 0.7.3 again.
Not sure it will fix that method, but maybe. I'll be back in a hour, I hope :)

**Comment by victordidenko** [comment] 2022-12-29 18:09
Nope, with 12.6.2 behaviour the same — 0.7.3 shows grey icons (grey rectangles actually), 0.7.3b1 and 0.7.3b2 works fine.

**Comment by freefelt** [comment] 2022-12-29 19:07
Thanks a lot! The fix will be in the next updates.

**Closed by freefelt** 2022-12-29 19:07 UTC
